# Mengizinkan koneksi dari IP mana saja (0.0.0.0) di port 1883
listener 1883 0.0.0.0

# Mengaktifkan WebSockets di port 9001 (Opsional, berguna jika nanti butuh direct test)
listener 9001
protocol websockets

# Mengizinkan koneksi tanpa password untuk kemudahan tahap development
# Nanti saat production, ini harus diubah ke 'false' dan menggunakan password file
allow_anonymous false

# Tambahkan referensi ke file password
password_file /mosquitto/config/pwfile

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
